### ISSUE TITLE
Drop the Entire hestiaRS and prepare hestiaNIM

### ISSUE THREAD

**Issue by corygalyna** [ZORALab/Hestia#104]
# Description
```
Please provide a short description of what feature you're looking forward to
enhance below. Please include the story behind your idea as well to give a
better visualization of your idea.
```
Since  we had unanimously agreed that Rust brought in more harms than good and go for Nim as a non-GC environment, we shall drop everything entirely and replace it with Nim.

[Discussion](https://github.com/ZORALab/Hestia/discussions/101)

# Expected Behavior
```
Please specify the expected behavior of your requested enhancement. Some great
and helpful pointers are your expected interface (e.g. command patterns,
simple sketches of the user interface, etc).
```
Rust artifacts are completely purged:

- [x] README.md
- [x] Documentation
- [x] Source codes
- [x] GitHub system
- [x] ZORALab interiors
- [x] Monteur build system

# Current Behavior
```
Please specify the current behavior (e.g. workaround, blockage, etc).
```
Rust is still under promotion.

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by hollowaykeanho** [comment]
New documentation completely dropped Rust.

**Comment by hollowaykeanho** [comment]
We don't use GitHuB CI so it is marked as completed by default.

**Comment by hollowaykeanho** [comment]
Done archiving. 96fc754d04dc375a5af0cf4a26ff0fe0346b5aed

**Comment by hollowaykeanho** [comment]
Released in version `v.1.2.0`.
