### ISSUE TITLE
Some __page.toml Custom Filepaths are Not Functioning

### ISSUE THREAD

**Issue by corygalyna** [ZORALab/Hestia#424]
# Description
```
Please provide a short description of what you have encountered below.
```
Although the archetypes' `__page.toml` allows customized source file location for:

```
...
Contributors = '__contributors.toml'
Thumbnails = '__thumbnails.toml'
Languages = '__languages.toml'
...
```

They aren't working at all. This can significantly reduces total read files for common files especially for large repo. Specifically, we can see `Thumbnails` as a great example.

# Expected Behavior
```
Please specify the expected behavior of your usage below.
```
They are all working properly.

# Current Behavior
```
Please specify the current behavior of software below.
```
Contributors, Thumbnails, Languages, and Assets are not working at all.

# Steps to Reproduce (COMPULSORY)
```
Please specify all the steps required to re-produce the problem.
```

# Attachments
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by hollowaykeanho** [comment]
Fixed in af26ada126335012544d4e15101ed3f5798a671c
