### ISSUE TITLE
What's the Community Guidelines?

### ISSUE THREAD

**Issue by corygalyna** [ZORALab/Hestia#58]
# Description
```
Please provide a short description of what feature you're looking forward to
add into the existing repository below. Please include the story behind your
idea as well to give a better visualization of your idea.
```
Looks like there isn't anything about communities for this project.

# Expected Behavior
```
Please specify the expected behavior of your requested feature. Some great and
helpful pointers are your expected interface (e.g. command patterns, simple
sketches of the user interface, etc).
```
Things I can think of:

- [ ] Clarify how ZORALab's going to profit from this (to steer clear of low-minded individuals).
- [x] Forums (use GitHub Discussion?)
- [x] Release strategies
- [ ] Sponsorship guidelines
- [ ] Code of Conducts
- [ ] Pull request policy and procedures
- [ ] Security reporting procedures

# Current Absent Behavior
```
Please specify the current behavior (e.g. workaround, blockage, etc).
```
All the above are missing.

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by hollowaykeanho** [comment]
I have yet to setup one. Currently working on Phase I release and getting started guides.

**Comment by hollowaykeanho** [comment]
You missed out security reporting procedures.

**Comment by CoryGalyna** [comment]
Done. Added. I assume you will setup a getting started page for that context?

**Comment by hollowaykeanho** [comment]
No.. avoid using additional forum (dicussion). Hard to maintain. Let's keep everything simple: in Issues.

Projects can triage all issues all together.

**Comment by hollowaykeanho** [comment]
> Done. Added. I assume you will setup a getting started page for that context?
Yes.
