### ISSUE TITLE
Write Up the Getting Started Section for hestiaHUGO

### ISSUE THREAD

**Issue by corygalyna** [ZORALab/Hestia#67]
# Description
```
Please provide a short description of what you have encountered below.
```
Seems like the last missing piece to keep this project friendly to use is the getting started pages where they are currently missing. 

# Link
```
Please provide the documentation link(s) below.
```
`/en/getting-started/*`

# Expected Presentation
```
Please specify the expected presentation of the documentation.
```
Getting started pages are up for `hestiaHUGO` so that the marketing and sharing efforts can begin. =)

- [x] tidying up hugo landing page.
- [x] construct hugo's getting started index page.
- [x] setup `hestiaHUGO` guide.
- [x] create new basic `hestiaHUGO` page guide.
- [ ] create new advanced `hestiaHUGO` page guide.
- [ ] publishing on GitHub/GitLab.
- [ ] publishing on Cloudflare Pages.
- [ ] reporting an issue guide page.

# Current Presentation
```
Please specify the current presentation of the documentation.
```
Getting started pages are still in placeholder mode.

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by hollowaykeanho** [comment]
Hugo getting started index page completed.

**Comment by CoryGalyna** [comment]
Demo repository: https://github.com/hollowaykeanho/DemoHestia

**Comment by hollowaykeanho** [comment]
Setup hugo guide page completed.

**Comment by CoryGalyna** [comment]
Any update? Can't wait to promote out. =)

**Comment by hollowaykeanho** [comment]
Working on the basic page in a separate repo. We have to get Issue #59 solved ASAP. Right now, with 80+ pages, it takes 2mins to perform precision compilation = not goood.

**Comment by CoryGalyna** [comment]
That's sting. We're so close.

**Comment by hollowaykeanho** [comment]
We don't have a choice... it's an open-source software. Self-reliance is a strict requirement since we won't offer commerical maintainence service for this project. Patience. I'm also eagar to graduate from this industry once and for all with this project as well. =)

Side-note: please take care over there. Glad to have you back.

**Comment by hollowaykeanho** [comment]
Done create new basic hestiaHUGO page guide. I'm going to block this and work out Issue #59 . The complations at 82 pages is too slow.

**Comment by GalynaCory** [comment]
Ensure Issue #59, #77, #79, and #80 are resolved before unblocking this issue. All of them have very disruptive influences to the content of the advanced guides.

**Comment by hollowaykeanho** [comment]
Unblocked as the `sites/` is now ready for publications with existing getting-started pages ported.

**Comment by hollowaykeanho** [comment]
Stop this. We're dropping Hugo.
