### ISSUE TITLE
Style the Debug Console for a Friendlier User Experience

### ISSUE THREAD

**Issue by corygalyna** [ZORALab/Hestia#77]
# Description
```
Please provide a short description of what feature you're looking forward to
enhance below. Please include the story behind your idea as well to give a
better visualization of your idea.
```
The Hestia Debug Console in hestiaHUGO is left untouched and presented in the ugliest possible manner of all things. Please style it so that it makes content development experience a lot less painful and easier to use.

# Expected Behavior
```
Please specify the expected behavior of your requested enhancement. Some great
and helpful pointers are your expected interface (e.g. command patterns,
simple sketches of the user interface, etc).
```
The Debug Console is no longer harassing the body layout. User does not need to inspect and delete the Debug Console every single time.

- [x] trigger interface
- [x] Data store display
- [x] Thumbnails display

# Current Behavior
```
Please specify the current behavior (e.g. workaround, blockage, etc).
```
The Debug Console is harassing the output body layout. User has to manually inspect the page and remove the console every single time.

Like this is bad for a blank page:

![06-check-rendered-website-400x460](https://user-images.githubusercontent.com/124406765/222038421-65951e44-64b1-4723-9193-90a1b3e7adcc.jpg)

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.

```

**Comment by hollowaykeanho** [comment]
On the page, a button is available at the bottom right:
![2023-05-03-16-54-54](https://user-images.githubusercontent.com/7259572/235872638-47a679df-30ec-4286-b63a-5f99451181be.jpg)

Clicking on it shall display a dialog:
![2023-05-03-16-54-29](https://user-images.githubusercontent.com/7259572/235872642-890702ac-10a0-4cd5-82c3-353128b65be5.jpg)

**Comment by hollowaykeanho** [comment]
Thumbnails renderer redesigned at 5d65498e99320ef9abe5a1bfd3b17628045dea02

**Comment by hollowaykeanho** [comment]
Re-styled data debugger console at commit: 5d65498e99320ef9abe5a1bfd3b17628045dea02

![2023-05-04-06-44-07](https://user-images.githubusercontent.com/7259572/236066884-72cef176-798c-430f-b6f0-41f7b1c83c89.jpg)

**Comment by corygalyna** [comment]
100% approved. Marked as completed. No further engineering efforts for this task.

**Comment by hollowaykeanho** [comment]
Transformed the entire thing into a styling resistant component and facilitated a config field for setting any debugger type (default to zoralab version) in commit dbc388965b4dd0c7622fc558c037d63168216dc2.

Existing solution crushed Google Chrome's tab's memory with overloading inline CSS codes and makes view-source completely unusable.

**Comment by hollowaykeanho** [comment]
Released in version `v.1.2.0`.
