### ISSUE TITLE
Ensure all __content.[FORMAT] can use all Go Template Pipelines

### ISSUE THREAD

**Issue by corygalyna** [ZORALab/Hestia#80]
# Description
```
Please provide a short description of what feature you're looking forward to
enhance below. Please include the story behind your idea as well to give a
better visualization of your idea.
```
Currently, all the `__content.[FORMAT]` are only able to be processed with available macro which were built from scratch. After the discovery from issue #59, it's entirely possible to pass in and render the `__content.[FORMAT]` page with the native pipelines. So, for the new `hestiaLIBS` in `hestiaHUGO`, please ensure all of them can be used just like any other layouts.

# Expected Behavior
```
Please specify the expected behavior of your requested enhancement. Some great
and helpful pointers are your expected interface (e.g. command patterns,
simple sketches of the user interface, etc).
```
all `__content.[FORMAT]` files can be used like any other normal layout file.

- [x] `__content.hestiaJSON`
- [x] `__content.hestiaHTML`
- [x] `__content.hestiaCSS`
- [x] `__content.hestiaJS`

# Current Behavior
```
Please specify the current behavior (e.g. workaround, blockage, etc).
```
`__content.[FORMAT]` is currently limited to macros developed from scratch like `express` and etc.

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by CoryGalyna** [comment]
Since this is heavily influencing the writing of getting started (Issue #67), please see it done before continue writing the them.

**Comment by hollowaykeanho** [comment]
__content.json, __content.ldjson, and __content.css all tested working and can use Go template functions by default commited in https://github.com/ZORALab/Hestia/commit/f0764c925fbea1ff00a862062697faad7b23b021.

**Comment by hollowaykeanho** [comment]
__content.hestiaHTML tested working and can use Go template functions by default commited in 32221e1.

**Comment by hollowaykeanho** [comment]
Released in version `v.1.2.0`.
