### ISSUE TITLE
Sponsorship from River Saxtons

### ISSUE THREAD

**Issue by hollowaykeanho** [ZORALab/Hestia#81]
# Description
```
Please provide a short description of what feature you're looking forward to
add into the existing repository below. Please include the story behind your
idea as well to give a better visualization of your idea.
```
I just received a 1-time sponsorship from River Saxtons who is now a finance sponsors. Let's add him/her in. It's aligned to the ZORALab's policy where any ZORALab member received a financial sponsorship, the party can be displayed here.

# Expected Behavior
```
Please specify the expected behavior of your requested feature. Some great and
helpful pointers are your expected interface (e.g. command patterns, simple
sketches of the user interface, etc).
```
River Saxtons is part of our financial sponsors.

# Current Absent Behavior
```
Please specify the current behavior (e.g. workaround, blockage, etc).
```
River Saxtons is not in our list.

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by GalynaCory** [comment]
Wait, you serious? Wow, congrats! I thought we were running dry with this project soon.

**Comment by hollowaykeanho** [comment]
Yeap. I just confirmed over my Stripe. Already in contact with the sponsor. Finally, a ray of light.

**Comment by GalynaCory** [comment]
You're SO gonna build me one after the 1.2 big release. Finally. The project caught attention. Let's continue to consolidate and assimilate.

In that case, we can really look into both low-level and high-level AI libraries (especially once we have access to micro-controllers) after the initialisation phases. Am proud of you. =)

**Comment by hollowaykeanho** [comment]
But first, let's get the company page and store upgrade first (about 70% completed). Been getting feedbacks asking exactly what business we're in.

**Comment by GalynaCory** [comment]
Yeah...and then get 1.2 up and release --> getting start guide --> Phase 2. People are paying attention now so let's not hold them up.

**Comment by hollowaykeanho** [comment]
Yes m'am.

**Comment by hollowaykeanho** [comment]
Haven't heard from our sponsor but he/she did followed my profile here: https://github.com/Xenador77. Thank you. We'll leave an open door for him/her to roll in future updates. For now, we will add the profile linking to his GitHub.

**Comment by hollowaykeanho** [comment]
Profile published on https://hestia.zoralab.com/en/.

**Comment by hollowaykeanho** [comment]
At River Saxton, if you have new updates, please don't hesitate to open a new ticket linking back to this one for us to roll out. Thank you once again.
