### ISSUE TITLE
Rename Rust Trademark to RS and Rust Logo to Ferries The Crab as Requested by Rust Foundation

### ISSUE THREAD

**Issue by hollowaykeanho** [ZORALab/Hestia#87]
# Description
```
Please provide a short description of what you have encountered below.
```
Rust Foundation is going to enforce a trademark policy where it prohibits the use of `Rust` but encourages `RS`. Hence, we have to update it. Moreover, they want the use of Ferris the crab rather than their gear logo to be used. To avoid these political drama, we have to change and comply accordingly.

Fortunately, these changes only affects documentation and Monteur automation tool. The codes and output packages are not affected.

Reference: https://docs.google.com/document/d/1ErZlwz9bbSI43dNo-rgQdkovm2h5ycuW220mWSOAuok/edit

# Expected Behavior
```
Please specify the expected behavior of your usage below.
```
All Rust trademark will now be changed to `RS`.

- [x] Issue Labels
- [x] Website Texts
- [x] Rust Logo
- [x] Text
- [x] Documentation
- [x] Crates

# Current Behavior
```
Please specify the current behavior of software below.
```
All Rust trademark is still using `Rust`.

# Steps to Reproduce (COMPULSORY)
```
Please specify all the steps required to re-produce the problem.
```
1) See website and GitHub codes.

# Attachments
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by GalynaCory** [comment]
Bummer. This is quite....unprofessional. Well, we don't have a choice but to move on.

**Comment by hollowaykeanho** [comment]
Yeah, while I'm currently rushing some private project. I will get it done as soon as possible.

**Comment by hollowaykeanho** [comment]
Rust documentation permits the word mark "Rust" to be used for designating the language used itself in text. Hence, we don't have to change the text.

**Comment by hollowaykeanho** [comment]
Crates was renamed to `hestiaRS` in 160b4d0a58ea6fe3ce078eda75019e88a1766d84

**Comment by hollowaykeanho** [comment]
At the moment, Rust logo is permitted since we're supporting it as a language: https://foundation.rust-lang.org/policies/logo-policy-and-media-guide/

Besides, the foundation team apologized for the chaos they had caused with the draft version https://www.theregister.com/2023/04/17/rust_foundation_apologizes_trademark_policy/.

**Comment by hollowaykeanho** [comment]
Switched to use Rust's Ferris in commit f60e02801dfbac887b38d8451c255c0901844715. Pending release due to documentations porting.

**Comment by hollowaykeanho** [comment]
Closed this issue as we are no longer supporting Rust in favor of Nim. See: https://github.com/ZORALab/Hestia/discussions/101.
