### ISSUE TITLE
__page+ld.json réutilisable?

### ISSUE THREAD

**Issue by SylvieGC** [ZORALab/Hestia#88]
# Description
```
Please provide a short description of what feature you're looking forward to
enhance below. Please include the story behind your idea as well to give a
better visualization of your idea.
```
aimer ce `__content.json`?

# Expected Behavior
```
Please specify the expected behavior of your requested enhancement. Some great
and helpful pointers are your expected interface (e.g. command patterns,
simple sketches of the user interface, etc).
```

# Current Behavior
```
Please specify the current behavior (e.g. workaround, blockage, etc).
```

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by hollowaykeanho** [comment]
possible. It's yet to be documented so we can consider updating the method based on your freeback. @GalynaCory , please check for resources.

**Comment by GalynaCory** [comment]
Phase 1.2. Might as well included in.

**Comment by hollowaykeanho** [comment]
LDSON is now capable of using Go template functions after commit 40ac56129e57757ca6ba46c63c8587aca5c2c8de. The entire data structure can now be constructed similar to `__content.json` type.

A new rendering function library is to be made solely for LDJSON since they're structured.

**Comment by hollowaykeanho** [comment]
LDSON base renderer is first made available under the commit: 14a3198961ac6893d1855bec760b2c2e42d1354b with `Person` and `Organization` both merged into as `Entity`.

The base renderer generates a foundation dataset for the user. Then, the user can use `__content.hestiaLDJSON` to further customize it matching the page's content.

The feature is reusable yet customizable and maintainable. Thus, this would be the way forward for scaling.

**Comment by hollowaykeanho** [comment]
Added `CreativeWork` in 5d2e054963289f8263985b931f4db300d00fc9af

**Comment by hollowaykeanho** [comment]
Added `WebSite` in bce9db22f8500803924f5dda17c7ca4fe97488bf

**Comment by hollowaykeanho** [comment]
Added `WebPage`.

**Comment by hollowaykeanho** [comment]
Released in version `v.1.2.0`.
