### ISSUE TITLE
Develop runtime Caches List using Global .Store instead of Scan All Pages

### ISSUE THREAD

**Issue by hollowaykeanho** [ZORALab/Hestia#91]
# Description
```
Please provide a short description of what feature you're looking forward to
enhance below. Please include the story behind your idea as well to give a
better visualization of your idea.
```
Right now, the only way to consolidate all caches were to scan every single page in the repo for `__caches.toml` and assemble a list. This is time consuming and `O(n)` which is not something we want. There is an idea where we use the global scratchpad to process and store the list at runtime. Then, when rendering is required, loads the list.

New API is to be developed for the job.

On paper, it should help #59. If integrated automatically into URL processor, then all used URL are automatically cached.

# Expected Behavior
```
Please specify the expected behavior of your requested enhancement. Some great
and helpful pointers are your expected interface (e.g. command patterns,
simple sketches of the user interface, etc).
```
No recursive scanning needed anymore except on first boot.

- [X] Added runtime .Scratch memory system.
- [x] Develop Caches API.
- [x] Upgrade Existing PWA Offline caches pipelines.

# Current Behavior
```
Please specify the current behavior (e.g. workaround, blockage, etc).
```
recursive scanning is performed to gather all offline caching list.

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by hollowaykeanho** [comment]
Added `.Scratch` persistent memory feature 7f820443a58ef8333025c469bdceec72100a2ae1.

**Comment by hollowaykeanho** [comment]
Added PWA offline caching APIs 27fbd1d6e0cdc81b49c8011b985eabdff635d618.

**Comment by hollowaykeanho** [comment]
Reverted implementations in f5b6c93820bbe1129d33742da0521a116e825596.

`.Scratch` is only at Page level context which defeats the purpose. Also, we don't have Mutex control if we want to use our write file method which will cause data race.

Hence, we can't proceed to forward so the idea is scrapped and reverted.

References:

1. https://gohugo.io/functions/scratch/
2. https://github.com/gohugoio/hugo/issues/5689
3. https://github.com/gohugoio/hugo/issues/5689

Closing this issue as 'will not fix'. If any similar feature is implemented for Hugo in the future, we can re-consider it.

**Comment by hollowaykeanho** [comment]
Found this https://gohugo.io/functions/store/ and implemented successfully.

**Comment by hollowaykeanho** [comment]
Pipeline upgraded.

**Comment by GalynaCory** [comment]
Finally. This will make a massive improvement.

**Comment by hollowaykeanho** [comment]
Released in version `v.1.2.0`.
