### ISSUE TITLE
Revisit Getting Started Guides After Hugo Facilitated Arguments Config Settings (Hugo Server)

### ISSUE THREAD

**Issue by corygalyna** [ZORALab/Hestia#93]
# Description
```
Please provide a short description of what you have encountered below.
```
Hugo ticket was triaged successfully as proposal: https://github.com/gohugoio/hugo/issues/10911. Once the ticket is closed, we will revisit the getting started guide to use `hugo server` natively.

# Link
```
Please provide the documentation link(s) below.
```
https://github.com/gohugoio/hugo/issues/10911

# Expected Presentation
```
Please specify the expected presentation of the documentation.
```
eliminate the need of using `server.cmd` and use `hugo server` natively.

# Current Presentation
```
Please specify the current presentation of the documentation.
```
`hugo server` requires a `server.cmd` script to operate.

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by hollowaykeanho** [comment]
Cory, I don't think we should get rid `server.cmd` as hugo is very inconsistent and we're facing a weird memory leak bug like [Issue 106](https://github.com/ZORALab/Hestia/issues/106). I think we should keep it so that our end users don't need to suffer what we got through. Please advise.

**Comment by corygalyna** [comment]
Ok. We won't get rid of it then. Then we'll close this tiket as won't implement.

**Comment by hollowaykeanho** [comment]
got it. TQ.
