### ISSUE TITLE
Someone Is Attempting to Overwrite Copyright HestiaUI Designs and Libraries ==> Rename components from _hestiaUI to _zoralab

### ISSUE THREAD

**Issue by corygalyna** [ZORALab/Hestia#99]
# Description
```
Please provide a short description of what you have encountered below.
```
Someone is attempting to copyright our hestiaUI designs at https://hestiaui.com/ with the domain name matching exactly and claims the copyright was started in year 2020.

@hollowaykeanho .

# Link
```
Please provide the documentation link(s) below.
```
https://hestiaui.com/

# Expected Presentation
```
Please specify the expected presentation of the documentation.
```
~~Document a trail here?~~

Rename:

- [x] `core_hestiaUI` --> `zoralab_core`
- [x] `font-notosans_hestiaUI` --> `zoralab_font_notosans`
- [x] `anchor_hestiaUI` --> `zoralab_anchor`
- [x] `code_hestiaUI` --> `zoralab_code`
- [x] `pre_hestiaUI` --> `zoralab_pre`
- [x] `catalog_hestiaUI` --> `zoralab_catalog`
- [x] `drawer_hestiaUI` --> `zoralab_drawer`
- [x] `toc_hestiaUI` --> `zoralab_toc`
- [x] `note_hestiaUI` --> `zoralab_note`
- [x] `note-error_hestiaUI` --> `zoralab_note_error`
- [x] `note-warning_hestiaUI` --> `zoralab_note_warning`
- [x] `note-success_hestiaUI` --> `zoralab_note_success`
- [x] `deflist_hestiaUI` --> `zoralab_deflist`
- [x] `olist_hestiaUI` --> `zoralab_olist`
- [x] `ulist_hestiaUI` --> `zoralab_ulist`
- [x] `divider_hestiaUI` --> `zoralab_divider`
- [x] `divider-cut_hestiaUI` --> `zoralab_divider_cut`
- [x] `divider-dashed_hestiaUI` --> `zoralab_divider_dashed`
- [x] `badge-shields_hestiaUI` --> `zoralab_badge_shields`
- [x] `button_hestiaUI` --> `zoralab_button`
- [x] `card_hestiaUI` --> `zoralab_card`
- [x] `blockquote_hestiaUI` --> `zoralab_blockquote`
- [x] `dialog_hestiaUI` --> `zoralab_dialog`
- [x] `picture_hestiaUI` --> `zoralab_picture`
- [x] `table_hestiaUI` --> `zoralab_table`
- [x] `form_hestiaUI` --> `zoralab_form`
- [x] `iframe_hestiaUI` --> `zoralab_iframe`
- [x] `carousel_hestiaUI` --> `zoralab_carousel`
- [x] `downarrow_joshuaMcD` --> `joshuamacdonald_downarrow`

# Current Presentation
```
Please specify the current presentation of the documentation.
```
-

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by hollowaykeanho** [comment]
![whois_hestiaui-com](https://user-images.githubusercontent.com/7259572/236601040-e83ea295-3d28-488d-9197-60446fadda53.png)

WhoIs query shown that the domain was registered on Year 2022, not Year 2020. 

```
commit 6ca3abfaa1a52f12924480442f68ab778b5d7148
Author: (Holloway) Chew, Kean Ho <kean.ho.chew@zoralab.com>
Date:   Sun Jul 17 11:22:34 2022 +0800

    root: initialized repository
    
    The patch is to initialize the repository.
    
    Signed-off-by: (Holloway) Chew, Kean Ho <kean.ho.chew@zoralab.com>
```

We may have to rebrand all components to `zoralab` instead since we're moving towards `hestiaGUI` library and most of our designs were originated from ZORALab anyway.

**Comment by hollowaykeanho** [comment]
Nope. Hestia was a re-born project from the now deprecated [ZORALab's Bissetii](https://bissetii.zoralab.com). We have a long history dated all the way back to 2016.

Leave it. I don't feel theatened but annoyed by these copycats.

**Comment by hollowaykeanho** [comment]
All components task list created. Begin renaming as it also solve `hestiaGO` and `hestiaRS` naming convention problems later in Phase 2.

**Comment by hollowaykeanho** [comment]
done in 20faadb5d0c07d3af6c2eb8be419d2e478b1cd9e

**Comment by corygalyna** [comment]
That was quick.

**Comment by hollowaykeanho** [comment]
Released in version `v.1.2.0`.
